### ISSUE TITLE
Classification example

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/cortipy#6]
Add text classification example/tutorial, specifically using the NuPIC kNN classifier.
- also gives NuPIC a much-needed classification demo
- iPython walkthrough would be good

**Comment by subutai** [comment]
Are you suggesting this example should be included in cortipy?  Not sure that makes sense - cortipy shouldn't depend on NuPIC.

**Comment by BoltzmannBrain** [comment]
my mistake, meant to add this to nupic.fluent :grin:
